# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '使用说明.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shiyongshuoming(object):
    def setupUi(self, shiyongshuoming):
        shiyongshuoming.setObjectName("shiyongshuoming")
        shiyongshuoming.resize(490, 200)
        shiyongshuoming.setMaximumSize(QtCore.QSize(490, 200))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        shiyongshuoming.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        shiyongshuoming.setWindowIcon(icon)
        shiyongshuoming.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton = QtWidgets.QPushButton(shiyongshuoming)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(shiyongshuoming)
        self.radioButton.setGeometry(QtCore.QRect(30, 80, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(shiyongshuoming)
        self.checkBox.setGeometry(QtCore.QRect(30, 130, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(shiyongshuoming)
        self.lineEdit.setGeometry(QtCore.QRect(260, 30, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(shiyongshuoming)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 80, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(shiyongshuoming)
        self.label.setGeometry(QtCore.QRect(260, 130, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(shiyongshuoming)
        QtCore.QMetaObject.connectSlotsByName(shiyongshuoming)

    def retranslateUi(self, shiyongshuoming):
        _translate = QtCore.QCoreApplication.translate
        shiyongshuoming.setWindowTitle(_translate("shiyongshuoming", "使用说明"))
        self.pushButton.setText(_translate("shiyongshuoming", "按钮，单击运行计算"))
        self.radioButton.setText(_translate("shiyongshuoming", "类型选择，只能选择一个"))
        self.checkBox.setText(_translate("shiyongshuoming", "是否选择，可以选择多个"))
        self.lineEdit.setText(_translate("shiyongshuoming", "文本框，计算值"))
        self.lineEdit_2.setText(_translate("shiyongshuoming", "文本框，输入值"))
        self.label.setText(_translate("shiyongshuoming", "本软件只能运行一个公式"))
import img_rc
