# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '声速马赫数计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtGui import *
import numpy as np
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("声速马赫数计算数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 声速马赫数(日期,气体类型,等熵指数,气体常数Rm,温度,声速,气体流动速度,马赫数,气体流动类型)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)

class Ui_shengshumaheshu(QMainWindow):
    def setupUi(self, shengshumaheshu):
        shengshumaheshu.setObjectName("shengshumaheshu")
        shengshumaheshu.setWindowModality(QtCore.Qt.NonModal)
        shengshumaheshu.setEnabled(True)
        shengshumaheshu.resize(620, 540)
        shengshumaheshu.setMaximumSize(QtCore.QSize(620, 540))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        shengshumaheshu.setFont(font)
        shengshumaheshu.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        shengshumaheshu.setWindowIcon(icon)
        shengshumaheshu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(shengshumaheshu)
        self.label.setGeometry(QtCore.QRect(0, 10, 620, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(shengshumaheshu)
        self.pushButton.setGeometry(QtCore.QRect(430, 460, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 180, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 280, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_4.setAccessibleName("")
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit.setGeometry(QtCore.QRect(280, 130, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(25、5, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 230, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_3.setAccessibleName("")
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(shengshumaheshu)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(shengshumaheshu)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(shengshumaheshu)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(shengshumaheshu)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(shengshumaheshu)
        self.label_10.setGeometry(QtCore.QRect(30, 430, 360, 90))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit_5.setGeometry(QtCore.QRect(280, 330, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setAccessibleName("")
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(shengshumaheshu)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(shengshumaheshu)
        self.lineEdit_6.setGeometry(QtCore.QRect(280, 380, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_6.setAccessibleName("")
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(shengshumaheshu)
        self.label_8.setGeometry(QtCore.QRect(30, 380, 240, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(shengshumaheshu)
        self.comboBox.setGeometry(QtCore.QRect(90, 70, 127, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(shengshumaheshu)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 50, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.checkBox_5 = QtWidgets.QCheckBox(shengshumaheshu)
        self.checkBox_5.setGeometry(QtCore.QRect(550, 330, 41, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_9 = QtWidgets.QLabel(shengshumaheshu)
        self.label_9.setGeometry(QtCore.QRect(250, 70, 150, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(160, 255, 17);")
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(shengshumaheshu)
        self.label_11.setGeometry(QtCore.QRect(410, 70, 150, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 243, 75);")
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(shengshumaheshu)
        QtCore.QMetaObject.connectSlotsByName(shengshumaheshu)

        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())
        self.lineEdit_6.setValidator(QDoubleValidator())

        self.lineEdit_2.setText("1.666")
        self.lineEdit_3.setText(str(float(8314.472/4.0026)))

        self.comboBox.currentIndexChanged.connect(self.box)
        self.pushButton.clicked.connect(self.jisuan)
        self.checkBox_5.clicked.connect(self.qiu)


    #气体选择
    def qiti(self):
        global A, R, Rm, M
        R = 8314.472
        A = self.comboBox.currentText()
        if A == "氦气":
            M = 4.0026;
            Rm = R / M
            self.lineEdit_2.setText("1.666")
            self.lineEdit_3.setText(str(Rm))
        if A == "氩气":
            M = 39.948;
            Rm = R / M
            self.lineEdit_2.setText("1.665")
            self.lineEdit_3.setText(str(Rm))
        if A == "氢气":
            M = 2.01588;
            Rm = R / M
            self.lineEdit_2.setText("1.405")
            self.lineEdit_3.setText(str(Rm))
        if A == "氧气":
            M = 32;
            Rm = R / M
            self.lineEdit_2.setText("1.396")
            self.lineEdit_3.setText(str(Rm))
        if A == "氮气":
            M = 28.0135;
            Rm = R / M
            self.lineEdit_2.setText("1.400")
            self.lineEdit_3.setText(str(Rm))
        if A == "二氧化碳":
            M = 44.0098;
            Rm = R / M
            self.lineEdit_2.setText("1.399")
            self.lineEdit_3.setText(str(Rm))
        if A == "空气":
            M = 28.959;
            Rm = R / M
            self.lineEdit_2.setText("1.400")
            self.lineEdit_3.setText(str(Rm))

    def box(self):
        self.qiti()
        self.jisuan()

    def qiu(self):
        if self.checkBox_5.isChecked()==False:
            self.lineEdit_6.clear()
            self.lineEdit_5.clear()
            self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        else:
            self.lineEdit_6.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.jisuan()


    def jisuan(self):
        self.qiti()
        global  k,R,T,a,M,V
        k=self.lineEdit_2.text()
        R=self.lineEdit_3.text()
        T=self.lineEdit_4.text()
        V=self.lineEdit_6.text()
        T0 = 273.15
        if k==None or R==None or T==None or k =="" or R =="" or T=="" or float(k)<0 or float(R)<0 or float(T)<0:
            QMessageBox.information(None, "提示说明", "输入不完整或错误，请检查后重新输入！", QMessageBox.Ok)
        else:
            T=float(T)+T0
            a=round(np.sqrt(float(k)*float(R)*T),5)
            self.lineEdit.setText(str(a))
            if self.checkBox_5.isChecked()==True:
                if V==None or V ==""or float(V)<0:
                    QMessageBox.information(None, "提示说明", "请输入气体流动速度！", QMessageBox.Ok)
                else:
                    M=round(float(V)/a,5)
                    self.lineEdit_5.setText(str(M))
                    self.liudong()
                    self.shuju()

    def liudong(self):
        if self.checkBox_5.isChecked() == True:
            global M
            if float(M)>1:
                self.label_11.setText("超声速流动")
            elif float(M)==1:
                self.label_11.setText("声速流动")
            else:
                self.label_11.setText("亚声速流动")

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        self.datetime()
        l=self.label_11.text()
        def sql_insert(con, data):
                cursor = con.cursor()
                cursor.execute("insert into 声速马赫数 (日期,气体类型,等熵指数,气体常数Rm,温度,声速,气体流动速度,马赫数,气体流动类型) values(?,?,?,?,?,?,?,?,?)", data)
                con.commit()
        data = (now_time,A,k,R,T,a,V,M,l)
        sql_insert(con, data)

    def retranslateUi(self, shengshumaheshu):
        _translate = QtCore.QCoreApplication.translate
        shengshumaheshu.setWindowTitle(_translate("shengshumaheshu", "声速马赫数V1.1 By ChengLiang"))
        self.label.setText(_translate("shengshumaheshu", "声速马赫数计算"))
        self.pushButton.setText(_translate("shengshumaheshu", "计算"))
        self.label_4.setText(_translate("shengshumaheshu", "等熵指数k "))
        self.label_5.setText(_translate("shengshumaheshu", "气体常数Rm（J/kgK）"))
        self.label_6.setText(_translate("shengshumaheshu", "温度T（℃）"))
        self.label_3.setText(_translate("shengshumaheshu", "声速a（m/s）"))
        self.label_10.setText(_translate("shengshumaheshu", "<html><head/><body><p align=\"center\">a=(kRmT)<span style=\" vertical-align:super;\">0.5 </span>    M=V/a</p><p align=\"center\">M＞1:超声速流动 M＜1:亚声速流动</p></body></html>"))
        self.label_7.setText(_translate("shengshumaheshu", "马赫数M "))
        self.label_8.setText(_translate("shengshumaheshu", "气体流动速度V（m/s）"))
        self.comboBox.setItemText(0, _translate("shengshumaheshu", "氦气"))
        self.comboBox.setItemText(1, _translate("shengshumaheshu", "氩气"))
        self.comboBox.setItemText(2, _translate("shengshumaheshu", "氢气"))
        self.comboBox.setItemText(3, _translate("shengshumaheshu", "氧气"))
        self.comboBox.setItemText(4, _translate("shengshumaheshu", "氮气"))
        self.comboBox.setItemText(5, _translate("shengshumaheshu", "二氧化碳"))
        self.comboBox.setItemText(6, _translate("shengshumaheshu", "空气"))
        self.label_2.setText(_translate("shengshumaheshu", "气体"))
        self.checkBox_5.setText(_translate("shengshumaheshu", "求"))
        self.label_9.setText(_translate("shengshumaheshu", "气体流动类型"))
import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_shengshumaheshu()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程