# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '定温放气计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtGui import *
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("定温放气计算数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 定温放气 (日期,气体类型,放气前容器中温度T1,吸收或放出的热量Q,放气前气体压力P1,放气后气体压力P2,等熵指数k,放气质量m,容器体积V,气体常数Rm)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)

class Ui_dingweifangqi(QMainWindow):
    def setupUi(self, dingweifangqi):
        dingweifangqi.setObjectName("dingweifangqi")
        dingweifangqi.setWindowModality(QtCore.Qt.NonModal)
        dingweifangqi.setEnabled(True)
        dingweifangqi.resize(660, 680)
        dingweifangqi.setMaximumSize(QtCore.QSize(660, 680))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        dingweifangqi.setFont(font)
        dingweifangqi.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dingweifangqi.setWindowIcon(icon)
        dingweifangqi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(dingweifangqi)
        self.label.setGeometry(QtCore.QRect(0, 10, 660, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(dingweifangqi)
        self.pushButton.setGeometry(QtCore.QRect(400, 70, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 180, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 280, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_4.setAccessibleName("")
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit.setGeometry(QtCore.QRect(320, 130, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 230, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_3.setAccessibleName("")
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(dingweifangqi)
        self.label_4.setGeometry(QtCore.QRect(20, 175, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dingweifangqi)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(dingweifangqi)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(dingweifangqi)
        self.label_3.setGeometry(QtCore.QRect(19, 130, 291, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(dingweifangqi)
        self.label_10.setGeometry(QtCore.QRect(30, 540, 601, 111))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 330, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setAccessibleName("")
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(dingweifangqi)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 380, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_6.setAccessibleName("")
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(dingweifangqi)
        self.label_8.setGeometry(QtCore.QRect(50, 380, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_7.setGeometry(QtCore.QRect(320, 430, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_7.setAccessibleName("")
        self.lineEdit_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setReadOnly(False)
        self.lineEdit_7.setPlaceholderText("")
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(dingweifangqi)
        self.label_9.setGeometry(QtCore.QRect(50, 480, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(dingweifangqi)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 480, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_8.setAccessibleName("")
        self.lineEdit_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setPlaceholderText("")
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_12 = QtWidgets.QLabel(dingweifangqi)
        self.label_12.setGeometry(QtCore.QRect(50, 430, 260, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox = QtWidgets.QComboBox(dingweifangqi)
        self.comboBox.setGeometry(QtCore.QRect(130, 70, 127, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(dingweifangqi)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 50, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(dingweifangqi)
        self.radioButton.setGeometry(QtCore.QRect(590, 380, 41, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(dingweifangqi)
        self.radioButton_2.setGeometry(QtCore.QRect(590, 430, 41, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(dingweifangqi)
        self.radioButton_3.setGeometry(QtCore.QRect(590, 230, 41, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(dingweifangqi)
        self.radioButton_4.setGeometry(QtCore.QRect(590, 280, 41, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")

        self.retranslateUi(dingweifangqi)
        QtCore.QMetaObject.connectSlotsByName(dingweifangqi)


        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())
        self.lineEdit_6.setValidator(QDoubleValidator())
        self.lineEdit_7.setValidator(QDoubleValidator())
        self.lineEdit_8.setValidator(QDoubleValidator())

        self.lineEdit_5.setText("1.666")
        self.lineEdit_8.setText(str(float(8314.472/4.0026)))

        self.comboBox.currentIndexChanged.connect(self.box)
        self.pushButton.clicked.connect(self.jisuan)
        self.radioButton.clicked.connect(self.qiu)
        self.radioButton_2.clicked.connect(self.qiu)
        self.radioButton_3.clicked.connect(self.qiu)
        self.radioButton_4.clicked.connect(self.qiu)

    def qiu(self):
        if self.radioButton.isChecked():
            self.lineEdit_7.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_6.clear()
        if self.radioButton_2.isChecked():
            self.lineEdit_6.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_7.clear()
        if self.radioButton_3.isChecked():
            self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_7.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_3.clear()
        if self.radioButton_4.isChecked():
            self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_7.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_4.clear()

    #气体选择
    def qiti(self):
        global R, Rm, M
        R = 8314.472
        A = self.comboBox.currentText()
        if A == "氦气":
            M = 4.0026;
            Rm = R / M
            self.lineEdit_5.setText("1.666")
            self.lineEdit_8.setText(str(Rm))
        if A == "氩气":
            M = 39.948;
            Rm = R / M
            self.lineEdit_5.setText("1.665")
            self.lineEdit_8.setText(str(Rm))
        if A == "氢气":
            M = 2.01588;
            Rm = R / M
            self.lineEdit_5.setText("1.405")
            self.lineEdit_8.setText(str(Rm))
        if A == "氧气":
            M = 32;
            Rm = R / M
            self.lineEdit_5.setText("1.396")
            self.lineEdit_8.setText(str(Rm))
        if A == "氮气":
            M = 28.0135;
            Rm = R / M
            self.lineEdit_5.setText("1.400")
            self.lineEdit_8.setText(str(Rm))
        if A == "二氧化碳":
            M = 44.0098;
            Rm = R / M
            self.lineEdit_5.setText("1.399")
            self.lineEdit_8.setText(str(Rm))
        if A == "空气":
            M = 28.959;
            Rm = R / M
            self.lineEdit_5.setText("1.400")
            self.lineEdit_8.setText(str(Rm))

    def box(self):
        self.qiti()
        self.jisuan()

    def jisuan(self):
        global T1, Q, T0, P1, P2, k, m, V, Rm
        T0 = 273.15
        T1 = self.lineEdit.text()
        Q = self.lineEdit_2.text()
        P1 = self.lineEdit_3.text()
        P2 = self.lineEdit_4.text()
        m = self.lineEdit_6.text()
        V = self.lineEdit_7.text()
        Rm = self.lineEdit_8.text()
        if self.radioButton.isChecked():
            if V==None or Rm==None or T1==None or P1==None or P2==None or\
                     V =="" or Rm =="" or T1 =="" or P1=="" or P2=="" or\
                    float(V) <0 or float(Rm)<0 or float(P1)<0 or float(P2)<0 :
                QMessageBox.information(None, "提示说明", "请正确输入数据！", QMessageBox.Ok)
            else:
                T1 = float(T1)+T0
                V = float(V)
                Rm = float(Rm)
                P1 = float(P1)
                P2 = float(P2)
                m=round(V*(P1-P2)/(Rm*T1),10)
                self.lineEdit_6.setText(str(m))
                self.qiti()
        if self.radioButton_2.isChecked():
            if m==None or  Rm==None or T1==None or P1==None or P2==None or\
                    m == "" or  Rm =="" or T1 =="" or P1=="" or P2=="" or\
                    float(m) <0 or  float(Rm)<0 or float(P1)<0 or float(P2)<0 :
                QMessageBox.information(None, "提示说明", "请正确输入数据！", QMessageBox.Ok)
            else:
                T1 = float(T1) + T0
                m = float(m)
                Rm = float(Rm)
                P1 = float(P1)
                P2 = float(P2)
                V=round(m/((P1-P2)/(Rm*T1)),10)
                self.lineEdit_7.setText(str(V))
                self.qiti()
        if self.radioButton_3.isChecked():
            if Q==None or  V==None or P2==None or\
                    Q == "" or  V =="" or  P2=="" or\
                    float(Q) <0 or  float(V)<0 or float(P2)<0 :
                QMessageBox.information(None, "提示说明", "请正确输入Q、P2、V数据！", QMessageBox.Ok)
            else:
                T1 = float(T1) + T0
                Rm = float(Rm)
                Q = float(Q)
                V = float(V)
                P2 = float(P2)
                P1=round(P2+Q/V,10)
                self.lineEdit_3.setText(str(P1))
                m = round(V * (P1 - P2) / (Rm * T1), 10)
                self.lineEdit_6.setText(str(m))
                self.qiti()
        if self.radioButton_4.isChecked():
            if Q==None or  V==None or P1==None or\
                    Q == "" or  V =="" or  P1=="" or\
                    float(Q) <0 or  float(V)<0 or float(P1)<0 :
                QMessageBox.information(None, "提示说明", "请正确输入Q、P1、V数据！", QMessageBox.Ok)
            else:
                T1 = float(T1) + T0
                Rm = float(Rm)
                Q = float(Q)
                V = float(V)
                P1 = float(P1)
                P2=round(P1-Q/V,10)
                self.lineEdit_4.setText(str(P2))
                m = round(V * (P1 - P2) / (Rm * T1), 10)
                self.lineEdit_6.setText(str(m))
                self.qiti()
        self.shuju()


    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        A = self.comboBox.currentText()
        k=self.lineEdit_5.text()
        T1=self.lineEdit.text()
        self.datetime()
        def sql_insert(con, data):
            cursor = con.cursor()
            cursor.execute("insert into 定温放气 (日期,气体类型,放气前容器中温度T1,吸收或放出的热量Q,放气前气体压力P1,放气后气体压力P2,等熵指数k,放气质量m,容器体积V,气体常数Rm) values(?,?,?,?,?,?,?,?,?,?)",
                           data)
            con.commit()
        data = (now_time,A, T1, Q, P1, P2, k, m, V, Rm)
        sql_insert(con, data)



    def retranslateUi(self, dingweifangqi):
        _translate = QtCore.QCoreApplication.translate
        dingweifangqi.setWindowTitle(_translate("dingweifangqi", "定温放气计算V1.1 By ChengLiang"))
        self.label.setText(_translate("dingweifangqi", "定温放气计算"))
        self.pushButton.setText(_translate("dingweifangqi", "计算"))
        self.label_4.setText(_translate("dingweifangqi", "吸收或放出的热量Q(J/kg)"))
        self.label_5.setText(_translate("dingweifangqi", "放气前气体压力P1（MPa）"))
        self.label_6.setText(_translate("dingweifangqi", "放气后气体压力P2（MPa）"))
        self.label_3.setText(_translate("dingweifangqi", "放气前容器中温度T1（℃）"))
        self.label_10.setText(_translate("dingweifangqi", "<html><head/><body><p align=\"center\">T<span style=\" vertical-align:sub;\">2</span>=T<span style=\" vertical-align:sub;\">1</span></p><p align=\"center\">P<span style=\" vertical-align:sub;\">2</span>=P<span style=\" vertical-align:sub;\">1</span>-Q/V</p><p align=\"center\">m=V(P<span style=\" vertical-align:sub;\">1</span>/R<span style=\" vertical-align:sub;\">m</span>T<span style=\" vertical-align:sub;\">1</span>-P<span style=\" vertical-align:sub;\">2</span>/R<span style=\" vertical-align:sub;\">m</span>T<span style=\" vertical-align:sub;\">2</span>)</p></body></html>"))
        self.label_7.setText(_translate("dingweifangqi", "等熵指数k"))
        self.label_8.setText(_translate("dingweifangqi", "放气质量m（g）"))
        self.label_9.setText(_translate("dingweifangqi", "气体常数Rm（J/kgK）"))
        self.label_12.setText(_translate("dingweifangqi", "容器体积V（mL）"))
        self.comboBox.setItemText(0, _translate("dingweifangqi", "氦气"))
        self.comboBox.setItemText(1, _translate("dingweifangqi", "氩气"))
        self.comboBox.setItemText(2, _translate("dingweifangqi", "氢气"))
        self.comboBox.setItemText(3, _translate("dingweifangqi", "氧气"))
        self.comboBox.setItemText(4, _translate("dingweifangqi", "氮气"))
        self.comboBox.setItemText(5, _translate("dingweifangqi", "二氧化碳"))
        self.comboBox.setItemText(6, _translate("dingweifangqi", "空气"))
        self.label_2.setText(_translate("dingweifangqi", "气体"))
        self.radioButton.setText(_translate("dingweifangqi", "求"))
        self.radioButton_2.setText(_translate("dingweifangqi", "求"))
        self.radioButton_3.setText(_translate("dingweifangqi", "求"))
        self.radioButton_4.setText(_translate("dingweifangqi", "求"))

import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_dingweifangqi()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程