# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '收缩喷管出口速度和流量计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
import numpy as np
from PyQt5.QtGui import *
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("收缩喷管出口速度和流量亚声速壅塞计算数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 收缩喷管出口速度和流量亚声速壅塞 (日期,气体类型,收缩喷管直径D,收缩喷管面积S,滞止压力P0,等熵指数κ,滞止密度ρ,出口压力P,出口速度v,质量流量Qm)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)


class Ui_shousuopenguan(QMainWindow):
    def setupUi(self, shousuopenguan):
        shousuopenguan.setObjectName("shousuopenguan")
        shousuopenguan.setWindowModality(QtCore.Qt.NonModal)
        shousuopenguan.setEnabled(True)
        shousuopenguan.resize(740, 600)
        shousuopenguan.setMaximumSize(QtCore.QSize(740, 600))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        shousuopenguan.setFont(font)
        shousuopenguan.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        shousuopenguan.setWindowIcon(icon)
        shousuopenguan.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(shousuopenguan)
        self.label.setGeometry(QtCore.QRect(0, 20, 740, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(shousuopenguan)
        self.pushButton.setGeometry(QtCore.QRect(650, 530, 60, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(shousuopenguan)
        self.label_9.setGeometry(QtCore.QRect(21, 460, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 210, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(shousuopenguan)
        self.radioButton.setGeometry(QtCore.QRect(330, 100, 191, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(shousuopenguan)
        self.radioButton_2.setGeometry(QtCore.QRect(550, 100, 161, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(shousuopenguan)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 144, 24))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(shousuopenguan)
        self.comboBox.setGeometry(QtCore.QRect(180, 100, 127, 28))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QtCore.QRect(380, 460, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_7.setClearButtonEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 310, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(380, 360, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(380, 410, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit.setGeometry(QtCore.QRect(380, 160, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(shousuopenguan)
        self.lineEdit_3.setGeometry(QtCore.QRect(380, 260, 330, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(shousuopenguan)
        self.label_8.setGeometry(QtCore.QRect(21, 405, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(shousuopenguan)
        self.label_4.setGeometry(QtCore.QRect(21, 210, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(shousuopenguan)
        self.label_5.setGeometry(QtCore.QRect(21, 260, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(shousuopenguan)
        self.label_6.setGeometry(QtCore.QRect(21, 310, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(shousuopenguan)
        self.label_7.setGeometry(QtCore.QRect(21, 360, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(shousuopenguan)
        self.label_3.setGeometry(QtCore.QRect(21, 160, 350, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.label_10 = QtWidgets.QLabel(shousuopenguan)
        self.label_10.setGeometry(QtCore.QRect(10, 515, 630, 60))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(shousuopenguan)
        QtCore.QMetaObject.connectSlotsByName(shousuopenguan)
        self.lineEdit_3.setText("1.666")
        self.radioButton.setChecked(True)
        self.lineEdit_7.setClearButtonEnabled(True)

        self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_5.setStyleSheet("background-color: rgb(85, 255, 255);")

        # 设置信号
        self.pushButton.clicked.connect(self.jisuan)
        self.radioButton_2.toggled.connect(self.cleck)
        self.radioButton.toggled.connect(self.cleck)
        self.comboBox.currentIndexChanged.connect(self.box)

        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())
        self.lineEdit_6.setValidator(QDoubleValidator())
        self.lineEdit_7.setValidator(QDoubleValidator())



    def retranslateUi(self, shousuopenguan):
        _translate = QtCore.QCoreApplication.translate
        shousuopenguan.setWindowTitle(_translate("shousuopenguan", "收缩喷管出口速度和流量(亚声速壅塞)计算V1.2 By ChengLiang"))
        self.label.setText(_translate("shousuopenguan", "收缩喷管出口速度和流量(亚声速壅塞)计算"))
        self.pushButton.setText(_translate("shousuopenguan", "计算"))
        self.label_9.setText(_translate("shousuopenguan", "质量流量Qm（g/s）"))
        self.radioButton.setText(_translate("shousuopenguan", "计算速度和流量"))
        self.radioButton_2.setText(_translate("shousuopenguan", "计算喷管直径"))
        self.label_2.setText(_translate("shousuopenguan", "气体等熵指数"))
        self.comboBox.setItemText(0, _translate("shousuopenguan", "氦气"))
        self.comboBox.setItemText(1, _translate("shousuopenguan", "氩气"))
        self.comboBox.setItemText(2, _translate("shousuopenguan", "氢气"))
        self.comboBox.setItemText(3, _translate("shousuopenguan", "氧气"))
        self.comboBox.setItemText(4, _translate("shousuopenguan", "氮气"))
        self.comboBox.setItemText(5, _translate("shousuopenguan", "空气"))
        self.comboBox.setItemText(6, _translate("shousuopenguan", "二氧化碳"))
        self.label_8.setText(_translate("shousuopenguan", "出口速度v（m/s）"))
        self.label_4.setText(_translate("shousuopenguan", "滞止压力P0（MPa）"))
        self.label_5.setText(_translate("shousuopenguan", "等熵指数κ "))
        self.label_6.setText(_translate("shousuopenguan", "滞止密度ρ（g/L）"))
        self.label_7.setText(_translate("shousuopenguan", "出口压力P（MPa）"))
        self.label_3.setText(_translate("shousuopenguan", "收缩喷管直径D（mm）"))
        self.label_10.setText(_translate("shousuopenguan", "速度v=(2*κ*P0(1-(P/P0)^0.5)/((κ-1)*ρ))^0.5""<br>"
                                              "流量Qm=A*(2*κ*P0*ρ/(κ-1)*((P/P0)^(2/κ)-(P/P0)^((κ+1)/κ)))"))

    #气体选择
    def qiti(self):
        A = self.comboBox.currentText()
        if A == "氦气":
            self.lineEdit_3.setText("1.666")
        if A == "氩气":
            self.lineEdit_3.setText("1.665")
        if A == "氢气":
            self.lineEdit_3.setText("1.405")
        if A == "氧气":
            self.lineEdit_3.setText("1.396")
        if A == "氮气":
            self.lineEdit_3.setText("1.400")
        if A == "空气":
            self.lineEdit_3.setText("1.400")
        if A == "二氧化碳":
            self.lineEdit_3.setText("1.399")

    def box(self):
        self.qiti()
        # self.jisuan()

    # 创建选择
    def cleck(self):
        if self.radioButton.isChecked():
            self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        elif self.radioButton_2.isChecked():
            self.lineEdit_7.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")

    # 创建计算
    def jisuan(self):
        global D,P0,κ,ρ,v,Qm,P,S
        D = self.lineEdit.text()
        P0 = self.lineEdit_2.text()
        κ = self.lineEdit_3.text()
        ρ = self.lineEdit_4.text()
        P = self.lineEdit_5.text()
        Qm = self.lineEdit_7.text()
        if self.radioButton.isChecked():
            if D == None or P0 == None or κ == None or ρ == None or D == "" or P0 == "" or κ == "" or ρ == "" or \
                float(D) < 0 or float(P0) < 0 or float(κ) < 0 or float(ρ) < 0 or P==None or P=="" or float(P)<0:
                QMessageBox.information(None, "使用提示", "壅塞流量计算数据不完整或错误，请检查后重新输入！", QMessageBox.Ok)
                self.qiti()
            else:
                P0 = float(self.lineEdit_2.text())
                κ = float(self.lineEdit_3.text())
                ρ = float(self.lineEdit_4.text())
                P = float(self.lineEdit_5.text())
                D = float(self.lineEdit.text())
                S = np.pi * np.power(D / 2, 2)
                v = round((np.power(2 * κ * P0 * (1 - np.power(P / P0, (κ - 1) / κ)) / (((κ - 1) * ρ)), 0.5)) * 1000,10)
                self.lineEdit_6.setText(str(v))
                Qm = round(S * np.power(2 * κ * P0 * ρ / (κ - 1) * (np.power(P / P0, 2 / κ) - np.power(P / P0, (κ + 1) / κ)),0.5), 10)
                self.lineEdit_7.setText(str(Qm))
        elif self.radioButton_2.isChecked():
            if Qm == None or P0 == None or κ == None or ρ == None or Qm == "" or P0 == "" or κ == "" or ρ == "" or \
                float(Qm) < 0 or float(P0) < 0 or float(κ) < 0 or float(ρ) < 0 or P==None or P=="" or float(P)<0:
                QMessageBox.information(None, "使用提示", "喷管直径计算数据不完整或错误，请检查后重新输入！", QMessageBox.Ok)
                self.qiti()
            else:
                P0 = float(self.lineEdit_2.text())
                κ = float(self.lineEdit_3.text())
                ρ = float(self.lineEdit_4.text())
                P = float(self.lineEdit_5.text())
                Qm = float(self.lineEdit_7.text())
                S = Qm / (np.power(2 * κ * P0 * ρ / (κ - 1) * (np.power(P / P0, 2 / κ) - np.power(P / P0, (κ + 1) / κ)), 0.5))
                D = round(2 * np.power(S / np.pi, 0.5), 10)
                self.lineEdit.setText(str(D))
                v = round(np.power(2 * κ * P0 * (1 - np.power(P / P0, (κ - 1) / κ)) / (((κ - 1) * ρ)), 0.5)*1000, 10)
                self.lineEdit_6.setText(str(v))
        self.shuju()

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        A = self.comboBox.currentText()
        k=self.lineEdit_5.text()
        T1=self.lineEdit.text()
        self.datetime()
        def sql_insert(con, data):
            cursor = con.cursor()
            cursor.execute("insert into 收缩喷管出口速度和流量亚声速壅塞 (日期,气体类型,收缩喷管直径D,收缩喷管面积S,滞止压力P0,等熵指数κ,滞止密度ρ,出口压力P,出口速度v,质量流量Qm) values(?,?,?,?,?,?,?,?,?,?)",
                           data)
            con.commit()
        data = (now_time,A,D,S,P0,κ,ρ,P,v,Qm)
        sql_insert(con, data)

import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_shousuopenguan()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
