import sqlite3
import pandas as pd
import pandas.io.sql as sql
#连接数据库

db=input("请输入数据库地址：")
con = sqlite3.connect(db)
#列出所有表
cursorObj = con.cursor()
cursorObj.execute('SELECT name from sqlite_master where type= "table"')
tables=cursorObj.fetchall()
print(tables)
l=len(tables)#查看数据库表数量
print(l)
tables = ','.join(str(i) for i in tables)
print(tables)
#查询数据表的数据
table_name = input("请输入查询的数据表名称：")
name = "'(" + table_name + ",)'"
rows = sql.read_sql('select * from ' + table_name + ';', con)
print(rows)
input("请输入回车退出")



# # con = sqlite3.connect('E:/Program Files/公式集合数据库.db')  #连接数据可
# def sql_fetch(con):
#     cursorObj = con.cursor()
#     cursorObj.execute('SELECT * FROM 定容放气') #选择数据表
#     rows = cursorObj.fetchall()
#     for row in rows:
#         print(row)
# sql_fetch(con)


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '打开数据库.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog
import pandas.io.sql as sql
import sqlite3


class Ui_opensqlite(QMainWindow):
    def setupUi(self, opensqlite):
        opensqlite.setObjectName("opensqlite")
        opensqlite.resize(940, 70)
        opensqlite.setMaximumSize(QtCore.QSize(940, 70))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        opensqlite.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        opensqlite.setWindowIcon(icon)
        opensqlite.setStyleSheet("background-color: rgb(255, 255, 255);\n""")
        self.label_2 = QtWidgets.QLabel(opensqlite)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 101, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(opensqlite)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 741, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(opensqlite)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 20, 31, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(opensqlite)
        QtCore.QMetaObject.connectSlotsByName(opensqlite)

        self.pushButton_2.clicked.connect(self.sqlite)

    def retranslateUi(self, opensqlite):
        _translate = QtCore.QCoreApplication.translate
        opensqlite.setWindowTitle(_translate("opensqlite", "打开数据库"))
        self.label_2.setText(_translate("opensqlite", "数据库"))
        self.lineEdit.setText(_translate("opensqlite", " "))
        self.pushButton_2.setText(_translate("opensqlite", "…"))

    def sqlite(self):
        FileName=QFileDialog.getOpenFileName(None,"选择数据库文件",".","*.db")#选取文件名
        FileName = ''.join(str(i) for i in FileName[0]) #获取文件名
        self.lineEdit.clear()
        self.lineEdit.setText(str(FileName))
        con = sqlite3.connect(FileName)
        # 列出所有表
        cursorObj = con.cursor()
        cursorObj.execute('SELECT name from sqlite_master where type= "table"')
        tables = cursorObj.fetchall()
        tables = ','.join(str(i) for i in tables)
        print(tables)
        # 查询数据表的数据
        table_name = input("请输入查询的数据表名称：")
        rows = sql.read_sql('select * from ' + table_name + ';', con)
        print(rows)



import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_opensqlite()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程