# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '气体常数R计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtGui import *
import sqlite3
import datetime
from sqlite3 import Error


#连接数据库
def sql_connection():
    try:
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 气体常数Rm (日期,气体,摩尔质量,常数Rm)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)


class Ui_qitichangshuR(QMainWindow):
    def setupUi(self, qitichangshuR):
        qitichangshuR.setObjectName("qitichangshuR")
        qitichangshuR.setWindowModality(QtCore.Qt.NonModal)
        qitichangshuR.setEnabled(True)
        qitichangshuR.resize(470, 330)
        qitichangshuR.setMaximumSize(QtCore.QSize(470, 330))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        qitichangshuR.setFont(font)
        qitichangshuR.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qitichangshuR.setWindowIcon(icon)
        qitichangshuR.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(qitichangshuR)
        self.label.setGeometry(QtCore.QRect(0, 20, 470, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        # self.pushButton = QtWidgets.QPushButton(qitichangshuR)
        # self.pushButton.setGeometry(QtCore.QRect(270, 260, 110, 40))
        # font = QtGui.QFont()
        # font.setFamily("黑体")
        # font.setPointSize(18)
        # self.pushButton.setFont(font)
        # self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        # self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(qitichangshuR)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(230, 80, 211, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(qitichangshuR)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 180, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(qitichangshuR)
        self.label_8.setGeometry(QtCore.QRect(30, 200, 410, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(qitichangshuR)
        self.label_9.setGeometry(QtCore.QRect(170, 260, 50, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(qitichangshuR)
        self.comboBox.setGeometry(QtCore.QRect(230, 260, 120, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(qitichangshuR)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 180, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(qitichangshuR)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 140, 211, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(qitichangshuR)
        QtCore.QMetaObject.connectSlotsByName(qitichangshuR)

        self.lineEdit_2.setText("4.0026")
        Rg = round(8314.47 / float(self.lineEdit_2.text()), 10)
        self.lineEdit.setText(str(Rg))

        self.lineEdit_2.setValidator(QDoubleValidator())  #只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())  # 只允许输入数字

        # 设置信号
        # self.pushButton.clicked.connect(self.jisuan)
        self.comboBox.currentIndexChanged.connect(self.box)
        self.lineEdit_2.editingFinished.connect(self.jisuan)

    def retranslateUi(self, qitichangshuR):
        _translate = QtCore.QCoreApplication.translate
        qitichangshuR.setWindowTitle(_translate("qitichangshuR", "气体常数Rm计算V1.1 By ChengLiang"))
        self.label.setText(_translate("qitichangshuR", "气体常数Rm计算"))
        # self.pushButton.setText(_translate("qitichangshuR", "计算"))
        self.label_3.setText(_translate("qitichangshuR", "气体常数Rm"))
        self.label_8.setText(_translate("qitichangshuR", "<html><head/><body><p>Rm=8314.47/M<span style=\" vertical-align:sub;\">r</span></p></body></html>"))
        self.label_9.setText(_translate("qitichangshuR", "气体"))
        self.comboBox.setItemText(0, _translate("qitichangshuR", "氦气"))
        self.comboBox.setItemText(1, _translate("qitichangshuR", "氩气"))
        self.comboBox.setItemText(2, _translate("qitichangshuR", "氢气"))
        self.comboBox.setItemText(3, _translate("qitichangshuR", "氧气"))
        self.comboBox.setItemText(4, _translate("qitichangshuR", "氮气"))
        self.comboBox.setItemText(5, _translate("qitichangshuR", "空气"))
        self.comboBox.setItemText(6, _translate("qitichangshuR", "二氧化碳"))
        self.label_4.setText(_translate("qitichangshuR", "气体摩尔质量Mr"))

    #气体选择
    def qitimoer(self):
        global A
        A = self.comboBox.currentText()
        if A == "氦气":
            self.lineEdit_2.setText("4.0026")
        if A == "氩气":
            self.lineEdit_2.setText("39.948")
        if A == "氢气":
            self.lineEdit_2.setText("2.01588")
        if A == "氧气":
            self.lineEdit_2.setText("32")
        if A == "氮气":
            self.lineEdit_2.setText("28.0135")
        if A == "空气":
            self.lineEdit_2.setText("28.959")
        if A == "二氧化碳":
            self.lineEdit_2.setText("44.0098")

    def box(self):
        self.qitimoer()
        self.jisuan()

    def jisuan(self):
        global Rm,Mr
        Mr=float(self.lineEdit_2.text())
        if Mr<=0 : #设置错误，数值返回
            QMessageBox.information(None, "使用提示", "输入错误，请检查后重新输入计算！", QMessageBox.Ok)
            self.qitimoer()
        else:
            Rm = round(8314.47 / Mr, 10)
            self.lineEdit.setText(str(Rm))
        self.shuju()

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        self.datetime()
        def sql_insert(con, data):
                cursor = con.cursor()
                cursor.execute("insert into 气体常数Rm (日期,气体,摩尔质量,常数Rm) values(?,?,?,?)", data)
                con.commit()
        data = (now_time,A, Mr,Rm)
        sql_insert(con, data)


import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_qitichangshuR()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程
