# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '湿度计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtGui import *
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("湿度计算数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 湿度 (日期,湿空气绝对湿度X,水蒸气质量Mv,湿空气体积V,空气相对湿度ψ,饱和湿空气的绝对湿度Xmax)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)


class Ui_shidu(QMainWindow):
    def setupUi(self, shidu):
        shidu.setObjectName("shidu")
        shidu.setWindowModality(QtCore.Qt.NonModal)
        shidu.setEnabled(True)
        shidu.resize(740, 420)
        shidu.setMaximumSize(QtCore.QSize(740, 420))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        shidu.setFont(font)
        shidu.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        shidu.setWindowIcon(icon)
        shidu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(shidu)
        self.label.setGeometry(QtCore.QRect(0, 20, 740, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(shidu)
        self.pushButton.setGeometry(QtCore.QRect(510, 350, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(shidu)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 140, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(shidu)
        self.lineEdit_4.setGeometry(QtCore.QRect(420, 240, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_4.setAccessibleName("")
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(shidu)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(420, 290, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setAccessibleName("")
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit = QtWidgets.QLineEdit(shidu)
        self.lineEdit.setGeometry(QtCore.QRect(420, 90, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(shidu)
        self.lineEdit_3.setGeometry(QtCore.QRect(420, 190, 290, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_3.setAccessibleName("")
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(shidu)
        self.label_4.setGeometry(QtCore.QRect(20, 135, 400, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(shidu)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 400, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(shidu)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 400, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(shidu)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 400, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(shidu)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 400, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.checkBox_2 = QtWidgets.QCheckBox(shidu)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 240, 121, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_10 = QtWidgets.QLabel(shidu)
        self.label_10.setGeometry(QtCore.QRect(20, 350, 390, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(shidu)
        QtCore.QMetaObject.connectSlotsByName(shidu)

        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())

        self.pushButton.clicked.connect(self.jisuan)
        self.checkBox_2.clicked.connect(self.xuanze)

    def xuanze(self):
        if self.checkBox_2.isChecked()==True:
            self.lineEdit_5.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.jisuan()
        else:
            self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")

    def jisuan(self):
        global X,Mv,V,ψ,Xmax
        X=self.lineEdit.text()
        Mv=self.lineEdit_2.text()
        V=self.lineEdit_3.text()
        ψ=self.lineEdit_4.text()
        Xmax = self.lineEdit_5.text()
        if Mv == None or V == None or Mv == "" or V == "" or float(Mv) < 0 or float(V) < 0:
            QMessageBox.information(None, "提示说明", "请输入正确的水蒸气质量Mv和湿空气体积V！", QMessageBox.Ok)
        else:
            X = float(Mv) / (float(V)/1000)
            self.lineEdit.setText(str(X))
            if self.checkBox_2.isChecked():
                if Xmax == None or  Xmax == "" or float(Xmax) < 0:
                    QMessageBox.information(None, "提示说明", "请输入正确的饱和湿空气的绝对湿度Xmax！", QMessageBox.Ok)
                else:
                    ψ=X/float(Xmax)
                    self.lineEdit_4.setText(str(ψ))
        self.shuju()

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        self.datetime()
        def sql_insert(con, data):
            cursor = con.cursor()
            cursor.execute("insert into 湿度 (日期,湿空气绝对湿度X,水蒸气质量Mv,湿空气体积V,空气相对湿度ψ,饱和湿空气的绝对湿度Xmax) values(?,?,?,?,?,?)",
                           data)
            con.commit()
        data = (now_time,X,Mv,V,ψ,Xmax)
        sql_insert(con, data)

    def retranslateUi(self, shidu):
        _translate = QtCore.QCoreApplication.translate
        shidu.setWindowTitle(_translate("shidu", "湿度计算V1.1 By ChengLiang"))
        self.label.setText(_translate("shidu", "湿度计算"))
        self.pushButton.setText(_translate("shidu", "计算"))
        self.label_4.setText(_translate("shidu", "水蒸气质量Mv（kg）"))
        self.label_5.setText(_translate("shidu", "湿空气体积V（L）"))
        self.label_6.setText(_translate("shidu", "空气相对湿度ψ（%）"))
        self.label_7.setText(_translate("shidu", "饱和湿空气的绝对湿度Xmax（kg/m3）"))
        self.label_3.setText(_translate("shidu", "湿空气绝对湿度X（kg/m3）"))
        self.checkBox_2.setText(_translate("shidu", "求相对湿度"))
        self.label_10.setText(_translate("shidu", "<html><head/><body><p>X=M<span style=\" vertical-align:sub;\">v</span>/V     ψ=X/X<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_shidu()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程