# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '版本说明.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_banbenshuoming(object):
    def setupUi(self, banbenshuoming):
        banbenshuoming.setObjectName("banbenshuoming")
        banbenshuoming.resize(1024, 900)
        banbenshuoming.setMaximumSize(QtCore.QSize(1024, 900))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        banbenshuoming.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        banbenshuoming.setWindowIcon(icon)
        banbenshuoming.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit = QtWidgets.QTextEdit(banbenshuoming)
        self.textEdit.setGeometry(QtCore.QRect(2, 0, 1020, 900))
        self.textEdit.setMaximumSize(QtCore.QSize(1020, 900))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(banbenshuoming)
        QtCore.QMetaObject.connectSlotsByName(banbenshuoming)

    def retranslateUi(self, banbenshuoming):
        _translate = QtCore.QCoreApplication.translate
        banbenshuoming.setWindowTitle(_translate("banbenshuoming", "版本说明"))
        self.textEdit.setHtml(_translate("banbenshuoming", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">版本V2.1 2023-05-16</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在其他公式目录下增加密封圈摩擦力计算。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">版本V2.0 2022-08-30</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">优化界面，在主界面显示选择公式的窗口并进行运行；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">完善个别公式的计算逻辑。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">版本V1.1 2022-06-05</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">每个公式增加计算结果数据库（SQlite），其中普通螺纹强度校核、梯形螺纹强度校核、过盈配合计算的数据库为各自独立的，其余公式的数据库合并在公式集合中；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">增加O形密封圈（轴沟槽、孔沟槽密封形式）拉伸率、压缩量计算公式，归类于密封公式中；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">定容充气和定压充气中增加容积、压力的求解算法；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">受力分析增加环形面积求解算法；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">增加软件介绍一栏（版本说明和使用说明）；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">增加数据库一栏，通过查询数据库查看计算数据，并且可以将数据导出；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">只能计算一个公式的情况还未解决，寻找解决方案中。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">版本V1.0 2022-05-18</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">优化界面模式，通过菜单式展现各公式选项，并对这些公式进行归类，分为气瓶相关公式、气体相关公式、其他公式、螺纹强度核算公式、密封公式；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">优化部分计算公式的逻辑计算；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">只能计算最后一次打开的公式，不能同时运行两个以上公式。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">版本V0.0 2022-04-29</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">设计各个公式的UI界面和计算逻辑，这些公式为压力容器壁厚计算、气瓶容积计算、气瓶工作容积或气量计算、范德瓦尔方程计算、线性流阻计算、非线性流阻计算、圆管体积流量计算、流量与电流的比拟计算、运动粘度计算、流体局部阻力系数计算、目和微米换算、定容放气计算、定容充气计算、气体单位转换、收缩喷管出口速度和流量(亚声速壅塞)计算、收缩喷管声速壅塞流量计算、不锈钢管折弯半径计算、导线电阻热量计算、过盈配合计算、普通螺纹强度校核、梯形螺纹强度校核、密封垫片密封计算、海拔高度压力温度计算、气体常数Rm计算、气体热流量计算、湿度计算、含湿量计算、比体积和密度计算、热力学能焓等熵指数计算、定压定容过程热量计算、多变过程热量计算、定温热量计算、定温充气计算、定温放气计算、绝热放气计算、绝热充气计算、声速马赫数计算、体积流量计算、受力计算；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">设计UI界面，通过按钮阵列式打开各个公式。</p></body></html>"))
import img_rc
