# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登录界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QMainWindow


class Ui_denglu(QMainWindow):
    def setupUi(self, denglu):
        denglu.setObjectName("denglu")
        denglu.setEnabled(True)
        denglu.resize(220, 130)
        denglu.setMaximumSize(QtCore.QSize(220, 130))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        denglu.setWindowIcon(icon)
        denglu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton = QtWidgets.QPushButton(denglu)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(denglu)
        self.label.setGeometry(QtCore.QRect(10, 22, 36, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(denglu)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 36, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(denglu)
        self.lineEdit.setGeometry(QtCore.QRect(52, 22, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("admin")
        self.lineEdit_2 = QtWidgets.QLineEdit(denglu)
        self.lineEdit_2.setGeometry(QtCore.QRect(52, 50, 133, 20))
        self.lineEdit_2.setMaxLength(8)
        self.lineEdit_2.setText("admin")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.retranslateUi(denglu)
        QtCore.QMetaObject.connectSlotsByName(denglu)

        self.pushButton.clicked.connect(self.dl)


    def retranslateUi(self, denglu):
        _translate = QtCore.QCoreApplication.translate
        denglu.setWindowTitle(_translate("denglu", "登录界面"))
        self.pushButton.setText(_translate("denglu", "登录"))
        self.label.setText(_translate("denglu", "账号："))
        self.label_2.setText(_translate("denglu", "密码："))

    def dl(self):
        a=self.lineEdit_2.text()
        b=self.lineEdit.text()
        print(a,b)
        if a=="admin" and b=="admin":
            QMessageBox.about(None,"提示","登录成功")
            self.open()
            Ui_denglu.exit()
        else:
            QMessageBox.about(None,"提示","账号或密码错误")

    def open(self):
        import 公式集合MDI
        self.公式集合MDI = QtWidgets.QMainWindow()
        self.u2 = 公式集合MDI.Ui_gongshijihe()  # 创建QT设计的窗体
        self.u2.setupUi(self.公式集合MDI)  # 创建窗口初始化
        self.公式集合MDI.show()  # 显示窗口
    import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_denglu()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程