# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '范德瓦尔方程.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
import numpy as np
from sympy import *
from PyQt5.QtGui import *
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("范德瓦尔方程数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 范德瓦尔方程 (日期,气体类型,表压P,温度T1,气体密度ρ,温度T2,T2温度下压力P1)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)

class Ui_fandewaer(QMainWindow):
    def setupUi(self, dingrongfangqi):
        dingrongfangqi.setObjectName("dingrongfangqi")
        dingrongfangqi.setWindowModality(QtCore.Qt.NonModal)
        dingrongfangqi.setEnabled(True)
        dingrongfangqi.resize(1230, 610)
        dingrongfangqi.setMaximumSize(QtCore.QSize(1230, 480))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        dingrongfangqi.setFont(font)
        dingrongfangqi.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dingrongfangqi.setWindowIcon(icon)
        dingrongfangqi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(dingrongfangqi)
        self.label.setGeometry(QtCore.QRect(0, 20, 1230, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(24)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(dingrongfangqi)
        self.pushButton.setGeometry(QtCore.QRect(500, 400, 110, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(dingrongfangqi)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 180, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(dingrongfangqi)
        self.radioButton.setGeometry(QtCore.QRect(400, 80, 260, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(dingrongfangqi)
        self.radioButton_2.setGeometry(QtCore.QRect(700, 80, 360, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(dingrongfangqi)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 50, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(dingrongfangqi)
        self.comboBox.setGeometry(QtCore.QRect(160, 80, 130, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(dingrongfangqi)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 280, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(dingrongfangqi)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(290, 330, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit = QtWidgets.QLineEdit(dingrongfangqi)
        self.lineEdit.setGeometry(QtCore.QRect(290, 130, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(dingrongfangqi)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(290, 230, 280, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setKerning(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(dingrongfangqi)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 250, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(dingrongfangqi)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 250, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(dingrongfangqi)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 250, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(dingrongfangqi)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 250, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(dingrongfangqi)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 250, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(dingrongfangqi)
        self.textBrowser.setGeometry(QtCore.QRect(590, 130, 611, 391))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(dingrongfangqi)
        QtCore.QMetaObject.connectSlotsByName(dingrongfangqi)

        self.radioButton.toggled.connect(self.cleck)
        self.radioButton_2.toggled.connect(self.cleck)
        self.comboBox.currentIndexChanged.connect(self.box)
        self.pushButton.clicked.connect(self.jisuan)

        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())




    def retranslateUi(self, dingrongfangqi):
        _translate = QtCore.QCoreApplication.translate
        dingrongfangqi.setWindowTitle(_translate("dingrongfangqi", "范德瓦尔方程计算V1.1 By ChengLiang ZBW"))
        self.label.setText(_translate("dingrongfangqi", "范德瓦尔方程计算"))
        self.pushButton.setText(_translate("dingrongfangqi", "计算"))
        self.radioButton.setText(_translate("dingrongfangqi", "计算非理想气体密度值"))
        self.radioButton_2.setText(_translate("dingrongfangqi", "已知压力和A温度求B温度下表压"))
        self.label_2.setText(_translate("dingrongfangqi", "气体"))
        self.comboBox.setItemText(0, _translate("dingrongfangqi", "氦气"))
        self.comboBox.setItemText(1, _translate("dingrongfangqi", "氩气"))
        self.comboBox.setItemText(2, _translate("dingrongfangqi", "氢气"))
        self.comboBox.setItemText(3, _translate("dingrongfangqi", "氧气"))
        self.comboBox.setItemText(4, _translate("dingrongfangqi", "氮气"))
        self.comboBox.setItemText(5, _translate("dingrongfangqi", "二氧化碳"))
        self.label_4.setText(_translate("dingrongfangqi", "A温度T1（℃）"))
        self.label_5.setText(_translate("dingrongfangqi", "气体密度ρ（g/mL）"))
        self.label_6.setText(_translate("dingrongfangqi", "B温度T2（℃）"))
        self.label_7.setText(_translate("dingrongfangqi", "B温度下压力P1（MPa）"))
        self.label_3.setText(_translate("dingrongfangqi", "表压P（MPa）"))
        self.textBrowser.setHtml(_translate("dingrongfangqi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:24pt;\">P=RT/(M(1/ρ-b/M))-ρ</span><span style=\" font-family:\'SimSun\'; font-size:24pt; vertical-align:super;\">2</span><span style=\" font-family:\'SimSun\'; font-size:24pt;\">a/M</span><span style=\" font-family:\'SimSun\'; font-size:24pt; vertical-align:super;\">2</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> P——气体绝对压力</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> R——气体常数</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> T——绝对温度</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> a——度量分子间引力的参数</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> b——每个分子平均占有的空间大小</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\"> M——摩尔质量</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">ρ——气体密度</span></p></body></html>"))



    #计算方式选择
    def cleck(self):
        if self.radioButton.isChecked():
            self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.lineEdit_4.clear()
            self.lineEdit_5.clear()
        if self.radioButton_2.isChecked():
            self.lineEdit.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")


    global Tc, Pc, M, Omega
    Tc = 5.25;
    Pc = 0.22697;
    M = 4.0026;
    Omega = -0.390;

    # 气体选择
    def qiti(self):
        global Tc, Pc, M, Omega
        A = self.comboBox.currentText()
        if A == "氦气":
            Tc = 5.25;
            Pc = 0.22697;
            M = 4.0026;
            Omega = -0.390;
        if A == "氩气":
            Tc = 150.86;
            Pc = 4.898;
            M = 39.948;
            Omega = 0.000;
        if A == "氢气":
            Tc = 33.2;
            Pc = 1.29728;
            M = 2.01588;
            Omega = -0.220;
        if A == "氧气":
            Tc = 154.59;
            Pc = 5.043;
            M = 32;
            Omega = 0.022;
        if A == "氮气":
            Tc = 126.1;
            Pc = 3.394;
            M = 28.0135;
            Omega = 0.040;
        if A == "二氧化碳":
            Tc = 304.1282;
            Pc = 7.3773;
            M = 44.0098;
            Omega = 0.22394;

    def box(self):
        self.qiti()
        self.jisuan()

    # 设置参数
    def canshu(self):
        global A,P1, T1, ρ1, ρ2, T2, m, V, P2, a, b, P0, T0, V0, R, Tc, Pc, m, Omega, Alpha, Rg, Vm, ρ,P
        P = self.lineEdit.text()
        T1 = self.lineEdit_2.text()
        T2 = self.lineEdit_4.text()
        P1=self.lineEdit_5.text()
        A = self.comboBox.currentText()


    #计算
    def jisuan(self):
        self.canshu()
        global P1, T1, ρ1, ρ2, T2, m, V, P2, a, b, P0, T0, V0, R, Tc, Pc, m, Omega, Alpha, Rg, Vm, ρ
        if self.radioButton.isChecked():
            self.qiyaP()
            self.shuju()
        if self.radioButton_2.isChecked():
            self.qiyaP()
            if T2 == None or T2 == "":
                QMessageBox.information(None, "使用提示", "请输入温度T2！", QMessageBox.Ok)
            else:
                T2 = float(T2) + T0
                Tr1 = T2 / Tc
                Alpha1 = np.power(1 + (0.48508 + 1.55171 * Omega - 0.15613 * np.power(Omega, 2)) * (1 - np.power(Tr1, 0.5)), 2)
                Vm1 = R / (float(ρ) * Rg)
                P1 = Symbol('P1')
                P1 = solve((R * T2 / (Vm1 - b) - a * Alpha1 / (Vm1 * (Vm1 + b)) - P1), P1)  # 计算B温度下压力值
                P1 = ','.join(str(i) for i in P1)  # 取结果的数值 不是复数 且去除括号
                P1 = float(P1) - P0
                self.lineEdit_5.setText(str(P1))
                self.shuju()


    def qiyaP(self):
        self.canshu()
        global P1, T1, ρ1, ρ2, T2, m, V, P2, a, b, P0, T0, V0, R, Tc, Pc, m, Omega, Alpha, Rg, Vm, ρ,P
        P0 = 101.325 * 0.001
        V0 = 22.414 * 1000
        T0 = 273.15
        R = 8.314472
        if T1 == None or T1 == "" or P == None or P == "" or float(P) < 0:
            QMessageBox.information(None, "使用提示", "请输入温度T1！表压P计算数据不完整或错误，请检查后重新输入！", QMessageBox.Ok)
        else:
            T1 = float(T1) + T0
            Tr = T1 / Tc
            a = 0.42748 * np.power(R, 2) * np.power(Tc, 2) / Pc
            b = 0.08664 * R * Tc / Pc
            Alpha = np.power(1 + (0.48508 + 1.55171 * Omega - 0.15613 * np.power(Omega, 2)) * (1 - np.power(Tr, 0.5)),2)
            Rg = P0 * V0 / T0 / M
            P = float(P) + P0
            ρ = Symbol('ρ')
            Vm = R / (ρ * Rg)
            ρ = solve([R * T1 / (Vm - b) - a * Alpha / (Vm * (Vm + b)) - P], [ρ])  # 计算密度
            ρ = ','.join(str(i) for i in ρ[0])  # 取结果的数值 不是复数 且去除括号
            self.lineEdit_3.setText(str(ρ))

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        self.datetime()
        P=self.lineEdit.text()
        T1 = self.lineEdit_2.text()
        P1=self.lineEdit_5.text()
        T2= self.lineEdit_4.text()
        ρ=self.lineEdit_3.text()
        def sql_insert(con, data):
            cursor = con.cursor()
            cursor.execute("insert into 范德瓦尔方程 (日期,气体类型,表压P,温度T1,气体密度ρ,温度T2,T2温度下压力P1) values(?,?,?,?,?,?,?)",
                           data)
            con.commit()
        data = (now_time,A,P,T1,ρ,T2,P1)
        sql_insert(con, data)


import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_fandewaer()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程