# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O形密封圈（轴沟槽、孔沟槽）计算.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtGui import *
import numpy as np
import sqlite3
import datetime
from sqlite3 import Error

#连接数据库
def sql_connection():
    try:
        # con = sqlite3.connect("不锈钢管折弯半径计算数据库.db")
        con = sqlite3.connect("公式集合数据库.db")
        return con
    except Error:
        print(Error)
#创建表
def sql_table(con):
    try:
        # 创建游标
        cursor = con.cursor()
        cursor.execute("create table 轴沟槽孔沟槽O形密封圈计算 (日期,密封圈密封类型,拉伸率ɑ,压缩率Y,槽公称直径D1,轴公称直径Dd,密封圈公称内径D,密封圈截面公称直径d,长轴a,短轴b,高度h)")
        # 提交事务
        con.commit()
    except Error:
        print(Error)
con = sql_connection()
sql_table(con)

class Ui_oxingmifengquanjisaun(QMainWindow):
    def setupUi(self, oxingmifengquanjisaun):
        oxingmifengquanjisaun.setObjectName("oxingmifengquanjisaun")
        oxingmifengquanjisaun.resize(850, 960)
        oxingmifengquanjisaun.setMaximumSize(QtCore.QSize(850, 960))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        oxingmifengquanjisaun.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/chengliang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        oxingmifengquanjisaun.setWindowIcon(icon)
        oxingmifengquanjisaun.setStyleSheet("background-color: rgb(255, 255, 255);\n""")
        self.label = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label.setGeometry(QtCore.QRect(0, 0, 850, 60))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_2.setGeometry(QtCore.QRect(110, 330, 170, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_3.setGeometry(QtCore.QRect(110, 370, 170, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_4.setGeometry(QtCore.QRect(70, 410, 210, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit.setGeometry(QtCore.QRect(300, 330, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 370, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 410, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.radioButton = QtWidgets.QRadioButton(oxingmifengquanjisaun)
        self.radioButton.setGeometry(QtCore.QRect(660, 140, 160, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setTabletTracking(False)
        self.radioButton.setAcceptDrops(False)
        self.radioButton.setToolTipDuration(-1)
        self.radioButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(oxingmifengquanjisaun)
        self.radioButton_2.setGeometry(QtCore.QRect(660, 80, 160, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(oxingmifengquanjisaun)
        self.pushButton.setGeometry(QtCore.QRect(375, 700, 100, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_5 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 490, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 530, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_8.setGeometry(QtCore.QRect(100, 570, 180, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_7.setGeometry(QtCore.QRect(19, 530, 260, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QtCore.QRect(300, 570, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("")
        self.lineEdit_7.setClearButtonEnabled(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_6 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_6.setGeometry(QtCore.QRect(40, 490, 240, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(oxingmifengquanjisaun)
        self.textBrowser.setGeometry(QtCore.QRect(510, 330, 311, 350))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_5.setGeometry(QtCore.QRect(70, 450, 210, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 450, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_9.setGeometry(QtCore.QRect(40, 610, 240, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QtCore.QRect(300, 610, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("")
        self.lineEdit_8.setClearButtonEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.graphicsView = QtWidgets.QGraphicsView(oxingmifengquanjisaun)
        self.graphicsView.setGeometry(QtCore.QRect(20, 60, 630, 250))
        self.graphicsView.setStyleSheet("background-image: url(:/PNG/O形密封圈.PNG);\n""border-width:0;border-style:outset")
        self.graphicsView.setObjectName("graphicsView")
        self.checkBox = QtWidgets.QCheckBox(oxingmifengquanjisaun)
        self.checkBox.setGeometry(QtCore.QRect(660, 200, 100, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(oxingmifengquanjisaun)
        self.checkBox_2.setGeometry(QtCore.QRect(660, 260, 90, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_10 = QtWidgets.QLabel(oxingmifengquanjisaun)
        self.label_10.setGeometry(QtCore.QRect(40, 650, 240, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(oxingmifengquanjisaun)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QtCore.QRect(300, 650, 200, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.textBrowser_2 = QtWidgets.QTextBrowser(oxingmifengquanjisaun)
        self.textBrowser_2.setGeometry(QtCore.QRect(130, 750, 590, 70))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(oxingmifengquanjisaun)
        self.textBrowser_3.setGeometry(QtCore.QRect(29, 840, 790, 100))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.retranslateUi(oxingmifengquanjisaun)
        QtCore.QMetaObject.connectSlotsByName(oxingmifengquanjisaun)

        # 只允许输入数字
        self.lineEdit.setValidator(QDoubleValidator())
        self.lineEdit_2.setValidator(QDoubleValidator())
        self.lineEdit_3.setValidator(QDoubleValidator())
        self.lineEdit_4.setValidator(QDoubleValidator())
        self.lineEdit_5.setValidator(QDoubleValidator())
        self.lineEdit_6.setValidator(QDoubleValidator())
        self.lineEdit_7.setValidator(QDoubleValidator())
        self.lineEdit_8.setValidator(QDoubleValidator())
        self.lineEdit_9.setValidator(QDoubleValidator())

        #创建信号
        self.radioButton.toggled.connect(self.cleck)
        self.radioButton_2.toggled.connect(self.cleck)
        self.checkBox.toggled.connect(self.leixingpanduan)
        self.checkBox_2.toggled.connect(self.leixingpanduan)
        self.checkBox_2.toggled.connect(self.cleck)
        self.pushButton.clicked.connect(self.jisuan)

    def canshu(self):
        global A,ɑ,Y,D1,Dd,D,d,a,b,h
        ɑ=self.lineEdit.text()
        Y=self.lineEdit_2.text()
        D1=self.lineEdit_3.text()
        Dd=self.lineEdit_4.text()
        D = self.lineEdit_5.text()
        d=self.lineEdit_6.text()
        a=self.lineEdit_7.text()
        b = self.lineEdit_8.text()
        h = self.lineEdit_9.text()
        if self.radioButton.isChecked():
                A=self.radioButton.text()
        if self.radioButton_2.isChecked():
                A=self.radioButton_2.text()

    #创建选择
    def cleck(self):
        if self.radioButton.isChecked() and self.checkBox_2.isChecked()==False:
                self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")
                self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.lineEdit_2.clear()
                self.lineEdit_3.clear()
        if self.radioButton_2.isChecked() and self.checkBox_2.isChecked()==False:
                self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
                self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.lineEdit_2.clear()
                self.lineEdit_4.clear()
        if self.checkBox_2.isChecked()==True:
                self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 255);")
                self.lineEdit_4.setStyleSheet("background-color: rgb(85, 255, 255);")

    #创建类型判断
    def leixingpanduan(self):
        if self.checkBox.isChecked() == False and self.checkBox_2.isChecked() == False:
            QMessageBox.information(None, "使用提示", "计算类型选择错误！", QMessageBox.Ok)
            self.checkBox.setChecked(True)
            self.checkBox_2.setChecked(True)
        if self.checkBox.isChecked() == False and self.checkBox_2.isChecked() == True:
            QMessageBox.information(None, "使用提示", "计算压缩率必须先计算拉伸率！", QMessageBox.Ok)
            self.checkBox.setChecked(True)
            self.checkBox_2.setChecked(True)

    def jisuan(self):
        global A, ɑ, Y, D1, Dd, D, d, a, b, h
        self.canshu()
        if self.checkBox.isChecked(): #拉伸率
           if D == None or D == "" or float(D) <= 0 or d == None or d == "" or float(d) <= 0:
                        QMessageBox.information(None, "使用提示", "请输入正确的密封圈内径D和截面直径d！", QMessageBox.Ok)
           if self.radioButton.isChecked():
                if Dd == None or Dd == "" or float(Dd) <= 0:
                        QMessageBox.information(None, "使用提示", "请输入正确的轴公称直径Dd！", QMessageBox.Ok)
                else:
                     ɑ=(float(Dd)+float(d))/(float(D)+float(d))
                     self.lineEdit.setText(str(ɑ))
           if self.radioButton_2.isChecked():
                if D1 == None or D1 == "" or float(D1) <= 0:
                        QMessageBox.information(None, "使用提示", "槽公称直径D1！", QMessageBox.Ok)
                else:
                     ɑ=(float(D1)+float(d))/(float(D)+float(d))
                     self.lineEdit.setText(str(ɑ))
           if self.checkBox_2.isChecked():#压缩率
                a = float(d)*np.sqrt(1 / (float(ɑ)*(1.35 - 0.35*float(ɑ))))
                b = float(d)*np.sqrt(1.35 / float(ɑ) - 0.35)
                h = (float(D1) - float(Dd)) / 2
                Y=(1-h/b)*100
                self.lineEdit_7.setText(str(a))
                self.lineEdit_8.setText(str(b))
                self.lineEdit_9.setText(str(h))
                self.lineEdit_2.setText(str(Y))
           self.shuju()

    def datetime(self):
        global now_time
        now_time= datetime.datetime.now().strftime("%Y.%m.%d %H:%M:%S")

    def shuju(self):
        self.datetime()
        def sql_insert(con, data):
                cursor = con.cursor()
                cursor.execute("insert into 轴沟槽孔沟槽O形密封圈计算 (日期,密封圈密封类型,拉伸率ɑ,压缩率Y,槽公称直径D1,轴公称直径Dd,密封圈公称内径D,密封圈截面公称直径d,长轴a,短轴b,高度h) values(?,?,?,?,?,?,?,?,?,?,?)", data)
                con.commit()
        data = (now_time,A,ɑ,Y,D1,Dd,D,d,a,b,h)
        sql_insert(con, data)


    def retranslateUi(self, oxingmifengquanjisaun):
        _translate = QtCore.QCoreApplication.translate
        oxingmifengquanjisaun.setWindowTitle(_translate("oxingmifengquanjisaun", "O形密封圈（轴沟槽、孔沟槽）计算V1.0 By ChengLiang"))
        self.label.setText(_translate("oxingmifengquanjisaun", "O形密封圈（轴沟槽、孔沟槽）计算"))
        self.label_2.setText(_translate("oxingmifengquanjisaun", "拉伸率ɑ"))
        self.label_3.setText(_translate("oxingmifengquanjisaun", "压缩率Y"))
        self.label_4.setText(_translate("oxingmifengquanjisaun", "槽公称直径D1 mm"))
        self.radioButton.setText(_translate("oxingmifengquanjisaun", "孔沟槽密封形式"))
        self.radioButton_2.setText(_translate("oxingmifengquanjisaun", "轴沟槽密封形式"))
        self.pushButton.setText(_translate("oxingmifengquanjisaun", "计算"))
        self.label_8.setText(_translate("oxingmifengquanjisaun", "长轴a mm"))
        self.label_7.setText(_translate("oxingmifengquanjisaun", "密封圈截面公称直径d mm"))
        self.label_6.setText(_translate("oxingmifengquanjisaun", "密封圈公称内径D mm"))
        self.textBrowser.setHtml(_translate("oxingmifengquanjisaun", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">轴沟槽密封形式拉伸率</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ɑ=(D<span style=\" vertical-align:sub;\">1</span>+d)/(D+d)</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">孔沟槽密封形式拉伸率</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ɑ=(D<span style=\" vertical-align:sub;\">d</span>+d)/(D+d)</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">压缩率</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Y=(1-h/b)×100%</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">a=d(1/(ɑ(1.35-0.35a)))^0.5</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">b=d(1.35/ɑ-0.35)^0.5</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h=(D<span style=\" vertical-align:sub;\">1</span>-D<span style=\" vertical-align:sub;\">d</span>)/2</p></body></html>"))
        self.label_5.setText(_translate("oxingmifengquanjisaun", "轴公称直径Dd mm"))
        self.label_9.setText(_translate("oxingmifengquanjisaun", "短轴b mm"))
        self.checkBox.setText(_translate("oxingmifengquanjisaun", "拉伸率ɑ"))
        self.checkBox_2.setText(_translate("oxingmifengquanjisaun", "压缩率Y"))
        self.label_10.setText(_translate("oxingmifengquanjisaun", "高度h mm"))
        self.textBrowser_2.setHtml(_translate("oxingmifengquanjisaun", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">   密封圈内径Dmm     ≤20       ＞20～50        ＞50</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">      拉伸率ɑ    1.06～1.04    1.05～1.03   1.04～1.02</p></body></html>"))
        self.textBrowser_3.setHtml(_translate("oxingmifengquanjisaun", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                   内部活动密封    固定密封、外部活动密封      螺纹连接件密封</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">压缩率Y              12%～17%            18%～22%                40%～45%</p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">最小允许压缩率Y<span style=\" vertical-align:sub;\">min</span>        7%                 11%                     35%</p></body></html>"))


import img_rc
import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    Mainwidow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_oxingmifengquanjisaun()  # 创建QT设计的窗体
    ui.setupUi(Mainwidow)  # 初始化设置
    Mainwidow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程